## This file is intended to store model parameters that describe physical properties of the drone.
#
# Remember to specify the unit and (if relevant) frame of reference.

gripper_length: 0.1


# Should be the geographical position of where we are flying the drone.
# It is used by ardupilot for correcting the earth magnetic field.
# Latitude, Longtitude, Altitude
# TODO: Find the position of Munich
operation_position : [-35.36294910983843, 149.16928445322435, 579.717312261560] # This is close to the standard position for the simulator tos start in.
